### ISSUE TITLE
scriptHandler removes bin/*.phar files from different packages

### ISSUE THREAD

**Issue by voda** [tommy-muehle/tooly-composer-script#12]
When I have a dependency which installs a .phar file into bin directory, then during ScriptHandler::installPharTools the phar gets removed.

Steps to reproduce:
* Create composer.json:
```json
{
	"name": "test/test",
	"require": {},
	"require-dev": {
		"phpstan/phpstan-shim": "^0.9.2",
		"tm/tooly-composer-script": "^1.2.5"
	},
	"scripts": {
		"post-install-cmd": [
			"Tooly\\ScriptHandler::installPharTools"
		],
		"post-update-cmd": [
			"Tooly\\ScriptHandler::installPharTools"
		]
	}
}
```
* run `composer install`
* vendor/bin now contains only `phpstan` file but phpstan/phpstan.shim package has two files specified in bin section of composer.json - https://github.com/phpstan/phpstan-shim/blob/master/composer.json#L11-L14

Expected is that after composer install two files (phpstan and phpstan.phar) files are in vendor/bin directory.

**Comment by tommy-muehle** [comment]
Hi @voda,

thanks for your feedback and the detailed issue report! As I developed tooly I was assuming that all PHAR files would be managed by tooly. So that [a cleanup](https://github.com/tommy-muehle/tooly-composer-script/blob/master/src/Script/Processor.php#L138) simply remove all PHAR files in the binary directories.

But anyway, can you please test this again with this tooly version?
```
"require-dev": {
    "tm/tooly-composer-script": "dev-master#bd936ef64693354e5700df8e5f8336333febfbdd"
  }
```

If this also works for you and I get the broken TravisCI stuff fixed, I'll release a new bugfix version.

Thanks,
Tommy

**Comment by voda** [comment]
Hi @tommy-muehle, tested the new version and it works as expected. Thanks
